language: rust

rust:
  # Feel free to bump this version if you need features of newer Rust.
  # Sync with badge in README.md
  - 1.26.1

cache:
  directories:
  - node_modules
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty
sudo: required

env:
  global:
  - CLIPPY_VERS=0.0.205
  - DEADLINKS_VERS=0.3.0
  - CARGO_INCREMENTAL=1
  matrix:
    - FEATURE=test

jobs:
  include:
  # Formatting & other lints that do not require compilation
  - env: FEATURE=lints
    install:
    - cargo-audit -V || cargo install cargo-audit --force
    - cargo-deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
    - cargo install --list
    - rustup component add rustfmt-preview
    - rustfmt -V
    - nvm install 8 && nvm use 8
    - npm install cspell
    - ./node_modules/.bin/cspell --version
    - npm install markdownlint-cli
    - ./node_modules/.bin/markdownlint --version
    script:
    - cargo fmt --all -- --write-mode=diff
    - ./node_modules/.bin/cspell src/**/*.rs
    - ./node_modules/.bin/cspell examples/**/*.rs
    - ./node_modules/.bin/cspell tests/**/*.rs
    - find . -not -path "./node_modules/*" -name "*.md" | xargs ./node_modules/.bin/cspell
    - find . -not -path "./node_modules/*" -name "*.md" | xargs ./node_modules/.bin/markdownlint
    - cargo doc --no-deps
    - cargo deadlinks --dir target/doc

  # Clippy linting
  - env: FEATURE=clippy
    rust: nightly-2018-05-26
    install:
    - cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
    script:
    - cargo clippy --all -- -D warnings

  # Tests
  - env: FEATURE=test
    script:
    - cargo test --all
    - cargo run --example print_version
