[package]
name = "os_type"
version = "2.0.0"
authors = ["Jan Schulte <hello@unexpected-co.de>"]
license = "MIT"
description = "Detect the operating system type"
repository = "https://github.com/schultyy/os_type"
[dependencies]
regex="^0.2.1"
